INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD



HEADERS += \
    $$PWD/w_bt_dish.h \
    $$PWD/w_bt_dish_table.h \
    $$PWD/w_bt_dish_paymode.h \
    $$PWD/w_bt_dish_suit.h \
    $$PWD/w_bt_dish_cookset.h \
    $$PWD/w_bt_dish_kitchenprinter.h \
    $$PWD/w_bt_dish_quit.h \
    $$PWD/w_m_member_paramset.h \
    $$PWD/w_m_member.h \
    $$PWD/w_m_member_statemanage.h \
    $$PWD/w_m_member_type.h \
    $$PWD/w_m_member_point.h \
    $$PWD/w_m_member_recharge.h \
    $$PWD/w_m_member_cardic.h \
    $$PWD/w_ds_sale_daybusiness.h \
    $$PWD/w_ds_sale_dishsaleout.h \
    $$PWD/w_ds_sale_qt.h \
    $$PWD/w_ds_sale_businessserach.h \
    $$PWD/w_ds_sale_salejournal.h \
    $$PWD/w_ds_sale_cashjournal.h \
    $$PWD/w_ds_sale_anticheckout.h \
    $$PWD/w_i_inventory_query.h \
    $$PWD/w_i_inventory_check.h \
    $$PWD/w_i_inventory_summaryquery.h \
    $$PWD/w_i_inventory_invoicing.h \
    $$PWD/w_rpt_report_promotionreport.h \
    $$PWD/w_rpt_report_dishquitreport.h \
    $$PWD/w_rpt_report_servantpromotquery.h \
    $$PWD/w_rpt_report_servicefeelowpinquery.h \
    $$PWD/w_rpt_report_directsalegrossprofitreport.h \
    $$PWD/w_rpt_report_tablebusinessreport.h \
    $$PWD/w_rpt_report_daybusinessreprot.h \
    $$PWD/w_rpt_report_categorysalesanalysis.h \
    $$PWD/w_rpt_report_periodbusinessanalysis.h \
    $$PWD/w_rpt_report_daymonweekanalysis.h \
    $$PWD/w_sys_manage_companyinformation.h \
    $$PWD/w_sys_manage_operatorinformation.h \
    $$PWD/w_sys_manage_operatorright.h \
    $$PWD/w_sys_manage_sqlcopy.h \
    $$PWD/w_sys_manage_basicdataimport.h \
    $$PWD/w_sys_manage_basicdataexport.h \
    $$PWD/w_sys_manage_businessdataclear.h \
    $$PWD/w_sys_manage_sysset.h \
    $$PWD/w_sys_manage_mysql.h \
    $$PWD/w_sys_manage_wirelessordermonitoring.h \
    $$PWD/w_sys_manage_sysreboot.h \
    $$PWD/w_rpt_report.h \
    $$PWD/w_bt_dish_base.h \
    $$PWD/backheader.h \
    $$PWD/w_m_member_list.h \
    $$PWD/w_i_inventory.h \
    $$PWD/w_sys_manage.h \
    $$PWD/w_sys_manage_cloudsync.h \
    $$PWD/w_sys_manage_cloudsync_transfer.h \
    $$PWD/w_sys_manage_basicdataimport_m_dialog.h \
    $$PWD/w_rpt_report_printformat.h \
    $$PWD/w_rpt_report_dataexport.h \
    $$PWD/w_bt_dish_kitchenprinter_printerset.h \
    $$PWD/w_rpt_report_footer.h \
    $$PWD/w_bt_dish_kitchen_dish.h \
    $$PWD/w_bt_dish_kitchen_dish_plan.h \
    $$PWD/back_view_dialog.h \
    $$PWD/w_sys_manage_outer_settings.h \
    $$PWD/w_sys_manage_outer_bill_preview.h \
    $$PWD/w_sys_manage_outer_pay_set.h \
    $$PWD/w_sys_manage_cloudsync_with_time.h \
    $$PWD/w_sys_manage_outer_pay_set_sql.h \
    $$PWD/w_m_member_list_select.h \
    $$PWD/w_rpt_report_frame.h \
    $$PWD/w_rpt_report_frame_btn_pageindex_.h \
    $$PWD/w_rpt_report_frame_btn_pageindex.h \
    $$PWD/w_rpt_report_frame_member.h \
    $$PWD/w_rpt_report_frame_dishsale.h \
    $$PWD/w_rpt_report_frame_cash.h \
    $$PWD/w_rpt_report_frame_saleflow.h \
    $$PWD/w_rpt_report_frame_cashflow.h \
    $$PWD/w_rpt_report_frame_dishsalerank.h \
    $$PWD/w_rpt_report_frame_businessdata.h \
    $$PWD/w_rpt_report_frame_uncheckout.h \
    $$PWD/w_rpt_report_frame_dishquit.h \
    $$PWD/w_rpt_report_frame_dishpromotion.h \
    $$PWD/w_rpt_report_frame_daybusiness.h \
    $$PWD/w_rpt_report_frame_daymothweek.h \
    $$PWD/w_rpt_report_frame_directsalegross.h \
    $$PWD/w_rpt_report_frame_servantpromotion.h \
    $$PWD/w_rpt_report_frame_tablebusiness.h \
    $$PWD/w_rpt_report_frame_servicelowcost.h \
    $$PWD/w_rpt_report_frame_periodbusiness.h \
    $$PWD/w_rpt_report_frame_categorybusiness.h \
    $$PWD/w_rpt_report_frame_select.h \
    $$PWD/w_bt_dish_kitchenprinter_printerset_port.h \
    $$PWD/w_bt_dish_kitchen_dish_state.h \
    $$PWD/back_view_svg_render.h \
    $$PWD/w_rpt_report_frame_shift.h \
    $$PWD/w_bt_dish_base_material.h \
    $$PWD/material_purchase_apply.h \
    $$PWD/material_purchase_in_storage.h \
    $$PWD/material_loss_apply.h \
    $$PWD/w_sys_manage_promotion_setting.h \
    $$PWD/w_rpt_report_material_sale.h \
    $$PWD/w_rpt_report_frame_material_saleflow.h \
    $$PWD/w_st_good_input_select_dish.h \
    $$PWD/w_rpt_report_frame_business_summary.h \
    $$PWD/w_sys_manage_cloudsync_cloud2.h \
    $$PWD/w_sys_manage_outer_settings_label.h \
    $$PWD/w_inventory_input.h \
    $$PWD/w_inventory_input_new.h \
    $$PWD/material_purchase_apply_new.h \
    $$PWD/w_inventory_draw.h \
    $$PWD/w_m_member_report_detail_dialog.h \
    $$PWD/w_sys_manage_sqlcopy_usb_select.h \
    $$PWD/w_m_member_telcoming.h \
    $$PWD/w_m_member_telcoming_table.h \
    $$PWD/w_rpt_report_frame_servantpromotquery.h \
    $$PWD/w_rpt_report_frame_limit.h \
    $$PWD/w_rpt_report_frame_material_saleflow2.h \


SOURCES += \
    $$PWD/w_bt_dish.cpp \
    $$PWD/w_bt_dish_table.cpp \
    $$PWD/w_bt_dish_paymode.cpp \
    $$PWD/w_bt_dish_suit.cpp \
    $$PWD/w_bt_dish_cookset.cpp \
    $$PWD/w_bt_dish_kitchenprinter.cpp \
    $$PWD/w_bt_dish_quit.cpp \
    $$PWD/w_m_member_paramset.cpp \
    $$PWD/w_m_member.cpp \
    $$PWD/w_m_member_statemanage.cpp \
    $$PWD/w_m_member_type.cpp \
    $$PWD/w_m_member_point.cpp \
    $$PWD/w_m_member_recharge.cpp \
    $$PWD/w_m_member_cardic.cpp \
    $$PWD/w_ds_sale_daybusiness.cpp \
    $$PWD/w_ds_sale_dishsaleout.cpp \
    $$PWD/w_ds_sale_qt.cpp \
    $$PWD/w_ds_sale_businessserach.cpp \
    $$PWD/w_ds_sale_salejournal.cpp \
    $$PWD/w_ds_sale_cashjournal.cpp \
    $$PWD/w_ds_sale_anticheckout.cpp \
    $$PWD/w_i_inventory_query.cpp \
    $$PWD/w_i_inventory_check.cpp \
    $$PWD/w_i_inventory_summaryquery.cpp \
    $$PWD/w_i_inventory_invoicing.cpp \
    $$PWD/w_rpt_report_promotionreport.cpp \
    $$PWD/w_rpt_report_dishquitreport.cpp \
    $$PWD/w_rpt_report_servantpromotquery.cpp \
    $$PWD/w_rpt_report_servicefeelowpinquery.cpp \
    $$PWD/w_rpt_report_directsalegrossprofitreport.cpp \
    $$PWD/w_rpt_report_tablebusinessreport.cpp \
    $$PWD/w_rpt_report_daybusinessreprot.cpp \
    $$PWD/w_rpt_report_categorysalesanalysis.cpp \
    $$PWD/w_rpt_report_periodbusinessanalysis.cpp \
    $$PWD/w_rpt_report_daymonweekanalysis.cpp \
    $$PWD/w_sys_manage_companyinformation.cpp \
    $$PWD/w_sys_manage_operatorinformation.cpp \
    $$PWD/w_sys_manage_operatorright.cpp \
    $$PWD/w_sys_manage_sqlcopy.cpp \
    $$PWD/w_sys_manage_basicdataimport.cpp \
    $$PWD/w_sys_manage_basicdataexport.cpp \
    $$PWD/w_sys_manage_businessdataclear.cpp \
    $$PWD/w_sys_manage_sysset.cpp \
    $$PWD/w_sys_manage_mysql.cpp \
    $$PWD/w_sys_manage_wirelessordermonitoring.cpp \
    $$PWD/w_sys_manage_sysreboot.cpp \
    $$PWD/w_bt_dish_base.cpp \
    $$PWD/backheader.cpp \
    $$PWD/w_m_member_list.cpp \
    $$PWD/w_rpt_report.cpp \
    $$PWD/w_i_inventory.cpp \
    $$PWD/w_sys_manage.cpp \
    $$PWD/w_sys_manage_cloudsync.cpp \
    $$PWD/w_sys_manage_cloudsync_transfer.cpp \
    $$PWD/w_sys_manage_basicdataimport_m_dialog.cpp \
    $$PWD/w_rpt_report_printformat.cpp \
    $$PWD/w_rpt_report_dataexport.cpp \
    $$PWD/w_bt_dish_kitchenprinter_printerset.cpp \
    $$PWD/w_rpt_report_footer.cpp \
    $$PWD/w_bt_dish_kitchen_dish.cpp \
    $$PWD/w_bt_dish_kitchen_dish_plan.cpp \
    $$PWD/back_view_dialog.cpp \
    $$PWD/w_sys_manage_outer_settings.cpp \
    $$PWD/w_sys_manage_outer_bill_preview.cpp \
    $$PWD/w_sys_manage_outer_pay_set.cpp \
    $$PWD/w_sys_manage_cloudsync_with_time.cpp \
    $$PWD/w_sys_manage_outer_pay_set_sql.cpp \
    $$PWD/w_m_member_list_select.cpp \
    $$PWD/w_rpt_report_frame.cpp \
    $$PWD/w_rpt_report_frame_btn_pageindex.cpp \
    $$PWD/w_rpt_report_frame_member.cpp \
    $$PWD/w_rpt_report_frame_dishsale.cpp \
    $$PWD/w_rpt_report_frame_cash.cpp \
    $$PWD/w_rpt_report_frame_saleflow.cpp \
    $$PWD/w_rpt_report_frame_cashflow.cpp \
    $$PWD/w_rpt_report_frame_dishsalerank.cpp \
    $$PWD/w_rpt_report_frame_businessdata.cpp \
    $$PWD/w_rpt_report_frame_uncheckout.cpp \
    $$PWD/w_rpt_report_frame_dishquit.cpp \
    $$PWD/w_rpt_report_frame_dishpromotion.cpp \
    $$PWD/w_rpt_report_frame_daybusiness.cpp \
    $$PWD/w_rpt_report_frame_daymothweek.cpp \
    $$PWD/w_rpt_report_frame_directsalegross.cpp \
    $$PWD/w_rpt_report_frame_servantpromotion.cpp \
    $$PWD/w_rpt_report_frame_tablebusiness.cpp \
    $$PWD/w_rpt_report_frame_servicelowcost.cpp \
    $$PWD/w_rpt_report_frame_periodbusiness.cpp \
    $$PWD/w_rpt_report_frame_categorybusiness.cpp \
    $$PWD/w_rpt_report_frame_select.cpp \
    $$PWD/w_bt_dish_kitchenprinter_printerset_port.cpp \
    $$PWD/w_bt_dish_kitchen_dish_state.cpp \
    $$PWD/back_view_svg_render.cpp \
    $$PWD/w_rpt_report_frame_shift.cpp \
    $$PWD/w_bt_dish_base_material.cpp \
    $$PWD/material_purchase_apply.cpp \
    $$PWD/material_purchase_in_storage.cpp \
    $$PWD/material_loss_apply.cpp \
    $$PWD/w_sys_manage_promotion_setting.cpp \
    $$PWD/w_rpt_report_material_sale.cpp \
    $$PWD/w_rpt_report_frame_material_saleflow.cpp \
    $$PWD/w_st_good_input_select_dish.cpp \
    $$PWD/w_rpt_report_frame_business_summary.cpp \
    $$PWD/w_sys_manage_cloudsync_cloud2.cpp \
    $$PWD/w_sys_manage_outer_settings_label.cpp \
    $$PWD/w_inventory_input.cpp \
    $$PWD/w_inventory_input_new.cpp \
    $$PWD/material_purchase_apply_new.cpp \
    $$PWD/w_inventory_draw.cpp \
    $$PWD/w_m_member_report_detail_dialog.cpp \
    $$PWD/w_sys_manage_sqlcopy_usb_select.cpp \
    $$PWD/w_m_member_telcoming.cpp \
    $$PWD/w_m_member_telcoming_table.cpp \
    $$PWD/w_rpt_report_frame_servantpromotquery.cpp \
    $$PWD/w_rpt_report_frame_limit.cpp \
    $$PWD/w_rpt_report_frame_material_saleflow2.cpp \

FORMS += \
    $$PWD/w_bt_dish_dialog.ui \
    $$PWD/w_bt_dish_typeset_dialog.ui \
    $$PWD/w_bt_dish_unitset_dialog.ui \
    $$PWD/w_bt_dish_table_new_dialog.ui \
    $$PWD/w_bt_dish_table_news_dialog.ui \
    $$PWD/w_bt_dish_table_tableset_dialog.ui \
    $$PWD/w_bt_dish_suit_dialog.ui \
    $$PWD/w_bt_dish_suit_new_dialog.ui \
    $$PWD/w_bt_dish_cookset_dialog.ui \
    $$PWD/w_bt_dish_cookset_specialcook_dialog.ui \
    $$PWD/w_bt_dish_cookset_dishset_dialog.ui \
    $$PWD/w_m_member_paramset_dialog.ui \
    $$PWD/w_m_member_dialog.ui \
    $$PWD/w_m_member_list_type_new_dialog.ui \
    $$PWD/w_m_member_list_recharge_dialog.ui \
    $$PWD/w_m_member_pwdchange_dialog.ui \
    $$PWD/w_m_member_sendcard_dialog.ui \
    $$PWD/w_m_member_statemanage_dialog.ui \
    $$PWD/w_m_member_state_dialog.ui \
    $$PWD/w_m_member_trans_dialog.ui \
    $$PWD/w_rpt_report_cashreport_dialog.ui \
    $$PWD/w_rpt_report_daymonweekanalysis_dialog.ui \
    $$PWD/w_rpt_report_directsalegrossprofitreport_dialog.ui \
    $$PWD/w_rpt_report_servantpromotquery_dialog.ui \
    $$PWD/w_rpt_report_tablebusinessreport_dialog.ui \
    $$PWD/w_rpt_report_daybusinessreprot_dialog.ui \
    $$PWD/w_rpt_report_categorysalesanalysis_dialog.ui \
    $$PWD/w_rpt_report_periodbusinessanalysis_dialog.ui \
    $$PWD/w_i_inventory_query_dialog.ui \
    $$PWD/w_i_inventory_summaryquery_dialog.ui \
    $$PWD/w_i_inventory_Invoicing_dialog.ui \
    $$PWD/w_i_inventory_check_dialog.ui \
    $$PWD/w_i_inventory_goodsinput_dialog.ui \
    $$PWD/w_sys_manage_companyinformation_dialog.ui \
    $$PWD/w_sys_manage_operatorright_dialog.ui \
    $$PWD/w_sys_manage_operatorright_rightcopy_dialog.ui \
    $$PWD/w_sys_manage_sqlcopy_dialog.ui \
    $$PWD/w_m_member_news_dialog.ui \
    $$PWD/w_m_member_point_recharge_dialog.ui \
    $$PWD/w_m_member_cardic_dialog.ui \
    $$PWD/w_sys_manage_basicdataimport_dialog.ui \
    $$PWD/w_sys_manage_businessdataclear_dialog.ui \
    $$PWD/w_sys_manage_sqlcopy_backup_strategy_dialog.ui \
    $$PWD/w_sys_manage_operatorinformation_dialog.ui \
    $$PWD/w_sys_manage_sqlcopy_soft_limit_dialog.ui \
    $$PWD/w_m_member_type_dialog.ui \
    $$PWD/w_bt_dish_paymode_dialog.ui \
    $$PWD/w_sys_manage_wirelessordermonitoring_dialog.ui \
    $$PWD/w_m_member_report_detail_dialog.ui \
    $$PWD/w_sys_manage_basicdataimport_m_dialog.ui \
    $$PWD/w_rpt_report_printformat.ui \
    $$PWD/w_rpt_report_dataexport.ui \
    $$PWD/w_bt_dish_kitchenprinter_printerset.ui \
    $$PWD/w_rpt_report_form.ui \
    $$PWD/w_rpt_report_footer.ui \
    $$PWD/w_bt_dish_kitchen_dish.ui \
    $$PWD/w_bt_dish_kitchen_dish_plan.ui \
    $$PWD/w_bt_dish_kitchen_dish_plan_new.ui \
    $$PWD/w_bt_dish_kitchen_dish_more.ui \
    $$PWD/w_bt_dish_kitchen_dish_param.ui \
    $$PWD/back_view_dialog.ui \
    $$PWD/w_sys_manage_outer_settings.ui \
    $$PWD/w_sys_manage_outer_bill_preview.ui \
    $$PWD/w_sys_manage_outer_pay_set.ui \
    $$PWD/w_sys_manage_outer_pay_set_ftp.ui \
    $$PWD/w_sys_manage_outer_pay_set_kechuan.ui \
    $$PWD/w_sys_manage_cloudsync_with_time.ui \
    $$PWD/w_sys_manage_cloudsync_with_time_running.ui \
    $$PWD/w_sys_manage_outer_pay_set_sql.ui \
    $$PWD/w_m_member_list_select.ui \
    $$PWD/w_rpt_report_frame.ui \
    $$PWD/w_rpt_report_frame_member.ui \
    $$PWD/w_rpt_report_frame_dishsale.ui \
    $$PWD/w_rpt_report_frame_cash.ui \
    $$PWD/w_rpt_report_frame_saleflow.ui \
    $$PWD/w_rpt_report_frame_cashflow.ui \
    $$PWD/w_rpt_report_frame_dishsalerank.ui \
    $$PWD/w_rpt_report_frame_businessdata.ui \
    $$PWD/w_rpt_report_frame_uncheckout.ui \
    $$PWD/w_rpt_report_frame_dishquit.ui \
    $$PWD/w_rpt_report_frame_dishpromotion.ui \
    $$PWD/w_rpt_report_frame_daybusiness.ui \
    $$PWD/w_rpt_report_frame_daymothweek.ui \
    $$PWD/w_rpt_report_frame_directsalegross.ui \
    $$PWD/w_rpt_report_frame_servantpromotion.ui \
    $$PWD/w_rpt_report_frame_tablebusiness.ui \
    $$PWD/w_rpt_report_frame_servicelowcost.ui \
    $$PWD/w_rpt_report_frame_periodbusiness.ui \
    $$PWD/w_rpt_report_frame_categorybusiness.ui \
    $$PWD/w_sys_manage_outer_pay_set_xiexin.ui \
    $$PWD/w_rpt_report_frame_select.ui \
    $$PWD/w_bt_dish_kitchenprinter_printerset_port.ui \
    $$PWD/w_bt_dish_kitchen_dish_state.ui \
    $$PWD/w_rpt_report_frame_shift.ui \
    $$PWD/w_sys_manage_outer_pay_set_isoft.ui \
    $$PWD/w_bt_dish_cookset_dishset.ui \
    $$PWD/w_bt_dish_new_dialog_2.ui \
    $$PWD/w_bt_dish_base_material.ui \
    $$PWD/material_purchase_apply.ui \
    $$PWD/w_sys_manage_promotion_setting.ui \
    $$PWD/w_rpt_report_material_sale.ui \
    $$PWD/w_rpt_report_frame_material_saleflow.ui \
    $$PWD/w_st_good_input_select_dish.ui \
    $$PWD/w_rpt_report_frame_business_summary.ui \
    $$PWD/w_bt_dish_table_new2.ui \
    $$PWD/w_sys_manage_cloudsync_cloud2.ui \
    $$PWD/w_sys_manage_promotion_setting_bath.ui \
    $$PWD/w_inventory_input.ui \
    $$PWD/w_inventory_input_new.ui \
    $$PWD/material_purchase_apply_new.ui \
    $$PWD/w_inventory_draw.ui \
    $$PWD/w_sys_manage_sqlcopy_usb_select.ui \
    $$PWD/w_m_member_telcoming.ui \
    $$PWD/w_m_member_telcoming_table.ui \
    $$PWD/w_bt_dish_cookset_typeset_dialog.ui \
    $$PWD/w_rpt_report_frame_servantpromotquery.ui \
    $$PWD/w_rpt_report_promotionreport.ui \
    $$PWD/w_rpt_report_servicefeelowpinquery_dialog.ui \
    $$PWD/w_rpt_report_frame_material_saleflow2.ui \
    back/w_bt_dish_paymode_set.ui \
